### ISSUE TITLE
Add feedback item to menu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rakekniven/mp3toolbox#31]
```
First idea
Using smtp to give feedback
```

Original issue reported on code.google.com by `mark.zie...@rakekniven.de` on 2 Jul 2012 at 6:35

**Comment by rakekniven** [comment]
SMTP is bad.
Better link to github page or offer email address to provide feedback.

**Comment by rakekniven** [comment]
Contact form of rakekniven.de will also work.
